# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Auction App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Auction App
  pod 'AlamofireImage'
  pod 'Parse'
  pod 'MessageInputBar'
                                       

  target 'Auction AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Auction AppUITests' do
    # Pods for testing
  end

end
